#define XA_EFFECT_TOUCH    0
#define XA_EFFECT_AURA     1
#define XA_EFFECT_PULSE    2
#define XA_MAX_EFFECT      2

#define XA_EFFECT_UNKNOWN  0
#define XA_EFFECT_ENERGY   1
#define XA_EFFECT_PSIONIC  2
#define XA_EFFECT_ELECTRO  3
#define XA_EFFECT_PARTICLE 4
#define XA_EFFECT_ORGANIC  5
#define XA_EFFECT_SYNTH    6