/decl/pronouns/skrell
	name = "Skrell"
	bureaucratic_term  = "Skrell"
	informal_term = "Skrell"

	He   = "Vi"
	he   = "vi"
	His  = "Vil"
	his  = "vil"
	him  = "vil"
	has  = "has"
	is   = "is"
	does = "does"
	self = "vilself"
	s    = "s"
	es   = "es"