/datum/antagonist/traitor/New()
	LAZYINITLIST(protected_jobs)
	protected_jobs   |= list(/datum/job/officer, /datum/job/warden, /datum/job/detective, /datum/job/captain, /datum/job/lawyer, /datum/job/hos)
	..()

/datum/antagonist/changeling/New()
	LAZYINITLIST(protected_jobs)
	protected_jobs   |= list(/datum/job/officer, /datum/job/warden, /datum/job/detective, /datum/job/captain, /datum/job/hos)
	..()

/datum/antagonist/godcultist/New()
	LAZYINITLIST(restricted_jobs)
	restricted_jobs  |= list(/datum/job/lawyer, /datum/job/captain, /datum/job/hos)
	LAZYINITLIST(protected_jobs)
	protected_jobs   |= list(/datum/job/officer, /datum/job/warden, /datum/job/detective)
	..()

/datum/antagonist/godcultist/New()
	LAZYINITLIST(blacklisted_jobs)
	blacklisted_jobs |= /datum/job/chaplain
	..()

/datum/antagonist/cultist/New()
	LAZYINITLIST(restricted_jobs)
	restricted_jobs  |= list(/datum/job/lawyer, /datum/job/captain, /datum/job/hos)
	LAZYINITLIST(protected_jobs)
	protected_jobs   |= list(/datum/job/officer, /datum/job/warden, /datum/job/detective)
	LAZYINITLIST(blacklisted_jobs)
	blacklisted_jobs |= list(/datum/job/chaplain, /datum/job/counselor)
	..()

/datum/antagonist/renegade/New()
	LAZYINITLIST(restricted_jobs)
	restricted_jobs  |= list(/datum/job/officer, /datum/job/warden, /datum/job/hos, /datum/job/captain)
	..()

/datum/antagonist/revolutionary/New()
	LAZYINITLIST(restricted_jobs)
	restricted_jobs  |= list(/datum/job/captain, /datum/job/hop, /datum/job/hos, /datum/job/chief_engineer, /datum/job/rd, /datum/job/cmo, /datum/job/lawyer)
	LAZYINITLIST(protected_jobs)
	protected_jobs   |= list(/datum/job/officer, /datum/job/warden, /datum/job/detective)
	..()

/datum/objective/heist/kidnap/New()
	LAZYINITLIST(roles)
	roles |= list(/datum/job/chief_engineer, /datum/job/rd, /datum/job/roboticist, /datum/job/chemist, /datum/job/engineer)
	..()
