DEFINE_STACK_SUBTYPES(tritium,        "tritium",                       gas/hydrogen/tritium,                  aerogel,          null)
DEFINE_STACK_SUBTYPES(deuterium,      "deuterium",                     gas/hydrogen/deuterium,                aerogel,          null)
DEFINE_STACK_SUBTYPES(iron,           "iron",                          solid/metal/iron,                      ingot,            null)
DEFINE_STACK_SUBTYPES(copper,         "copper",                        solid/metal/copper,                    ingot,            null)
DEFINE_STACK_SUBTYPES(sandstone,      "sandstone",                     solid/stone/sandstone,                 brick,            null)
DEFINE_STACK_SUBTYPES(marble,         "marble",                        solid/stone/marble,                    brick,            null)
DEFINE_STACK_SUBTYPES(basalt,         "basalt",                        solid/stone/basalt,                    brick,            null)
DEFINE_STACK_SUBTYPES(concrete,       "concrete",                      solid/stone/concrete,                  brick,            null)
DEFINE_STACK_SUBTYPES(graphite,       "graphite",                      solid/graphite,                        brick,            null)
DEFINE_STACK_SUBTYPES(diamond,        "diamond",                       solid/gemstone/diamond,                gemstone,         null)
DEFINE_STACK_SUBTYPES(uranium,        "uranium",                       solid/metal/uranium,                   puck,             null)
DEFINE_STACK_SUBTYPES(plastic,        "plastic",                       solid/organic/plastic,                 panel,            null)
DEFINE_STACK_SUBTYPES(fiberglass,     "fiberglass",                    solid/fiberglass,                      sheet/reinforced, null)
DEFINE_STACK_SUBTYPES(gold,           "gold",                          solid/metal/gold,                      ingot,            null)
DEFINE_STACK_SUBTYPES(silver,         "silver",                        solid/metal/silver,                    ingot,            null)
DEFINE_STACK_SUBTYPES(platinum,       "platinum",                      solid/metal/platinum,                  ingot,            null)
DEFINE_STACK_SUBTYPES(mhydrogen,      "metallic hydrogen",             solid/metallic_hydrogen,               segment,          null)
DEFINE_STACK_SUBTYPES(osmium,         "osmium",                        solid/metal/osmium,                    ingot,            null)
DEFINE_STACK_SUBTYPES(ocp,            "osmium-carbide plasteel",       solid/metal/plasteel/ocp,              sheet/reinforced, null)
DEFINE_STACK_SUBTYPES(steel,          "steel",                         solid/metal/steel,                     sheet,            null)
DEFINE_STACK_SUBTYPES(aluminium,      "aluminium",                     solid/metal/aluminium,                 sheet/shiny,      null)
DEFINE_STACK_SUBTYPES(titanium,       "titanium",                      solid/metal/titanium,                  sheet/reinforced, null)
DEFINE_STACK_SUBTYPES(plasteel,       "plasteel",                      solid/metal/plasteel,                  sheet/reinforced, null)
DEFINE_STACK_SUBTYPES(wood,           "wood",                          solid/organic/wood/oak,                plank,            null)
DEFINE_STACK_SUBTYPES(mahogany,       "mahogany",                      solid/organic/wood/mahogany,           plank,            null)
DEFINE_STACK_SUBTYPES(maple,          "maple",                         solid/organic/wood/maple,              plank,            null)
DEFINE_STACK_SUBTYPES(ebony,          "ebony",                         solid/organic/wood/ebony,              plank,            null)
DEFINE_STACK_SUBTYPES(walnut,         "walnut",                        solid/organic/wood/walnut,             plank,            null)
DEFINE_STACK_SUBTYPES(bamboo,         "bamboo",                        solid/organic/wood/bamboo,             plank,            null)
DEFINE_STACK_SUBTYPES(yew,            "yew",                           solid/organic/wood/yew,                plank,            null)
DEFINE_STACK_SUBTYPES(wood,           "wood",                          solid/organic/wood/oak,                log,              null)
DEFINE_STACK_SUBTYPES(mahogany,       "mahogany",                      solid/organic/wood/mahogany,           log,              null)
DEFINE_STACK_SUBTYPES(maple,          "maple",                         solid/organic/wood/maple,              log,              null)
DEFINE_STACK_SUBTYPES(ebony,          "ebony",                         solid/organic/wood/ebony,              log,              null)
DEFINE_STACK_SUBTYPES(walnut,         "walnut",                        solid/organic/wood/walnut,             log,              null)
DEFINE_STACK_SUBTYPES(bamboo,         "bamboo",                        solid/organic/wood/bamboo,             log,              null)
DEFINE_STACK_SUBTYPES(yew,            "yew",                           solid/organic/wood/yew,                log,              null)
DEFINE_STACK_SUBTYPES(cardboard,      "cardboard",                     solid/organic/cardboard,               cardstock,        null)
DEFINE_STACK_SUBTYPES(leather,        "leather",                       solid/organic/leather,                 skin,             null)
DEFINE_STACK_SUBTYPES(synthleather,   "synthleather",                  solid/organic/leather/synth,           skin,             null)
DEFINE_STACK_SUBTYPES(chitin,         "chitin",                        solid/organic/leather/chitin,          skin,             null)
DEFINE_STACK_SUBTYPES(bone,           "bone",                          solid/organic/bone,                    bone,             null)
DEFINE_STACK_SUBTYPES(glass,          "glass",                         solid/glass,                           pane,             null)
DEFINE_STACK_SUBTYPES(borosilicate,   "borosilicate glass",            solid/glass/borosilicate,              pane,             null)
DEFINE_STACK_SUBTYPES(aliumium,       "aliumium",                      solid/metal/aliumium,                  cubes,            null)
DEFINE_STACK_SUBTYPES(rglass,         "reinforced glass",              solid/glass,                           pane,             /decl/material/solid/metal/steel)
DEFINE_STACK_SUBTYPES(rborosilicate,  "reinforced borosilicate glass", solid/glass/borosilicate,              pane,             /decl/material/solid/metal/steel)
DEFINE_STACK_SUBTYPES(zinc,           "zinc",                          solid/metal/zinc,                      ingot,            null)
DEFINE_STACK_SUBTYPES(tin,            "tin",                           solid/metal/tin,                       ingot,            null)
DEFINE_STACK_SUBTYPES(lead,           "lead",                          solid/metal/lead,                      ingot,            null)
DEFINE_STACK_SUBTYPES(brass,          "brass",                         solid/metal/brass,                     ingot,            null)
DEFINE_STACK_SUBTYPES(bronze,         "bronze",                        solid/metal/bronze,                    ingot,            null)
DEFINE_STACK_SUBTYPES(chromium,       "chromium",                      solid/metal/chromium,                  ingot,            null)
DEFINE_STACK_SUBTYPES(blackbronze,    "black bronze",                  solid/metal/blackbronze,               ingot,            null)
DEFINE_STACK_SUBTYPES(redgold,        "red gold",                      solid/metal/redgold,                   ingot,            null)
DEFINE_STACK_SUBTYPES(stainlesssteel, "stainless steel",               solid/metal/stainlesssteel,            ingot,            null)
DEFINE_STACK_SUBTYPES(ice,            "ice",                           liquid/water,                          cubes,            null)
DEFINE_STACK_SUBTYPES(nutriment,      "nutriment",                     liquid/nutriment,                      segment,          null)

DEFINE_STACK_SUBTYPES(steel,          "steel",                         solid/metal/steel,                     rods,             null)
DEFINE_STACK_SUBTYPES(plastic,        "plastic",                       solid/organic/plastic,                 rods,             null)
DEFINE_STACK_SUBTYPES(aluminium,      "aluminium",                     solid/metal/aluminium,                 rods,             null)
DEFINE_STACK_SUBTYPES(titanium,       "titanium",                      solid/metal/titanium,                  rods,             null)

DEFINE_STACK_SUBTYPES(cotton,         "cotton",                        solid/organic/cloth,                   thread,           null)
DEFINE_STACK_SUBTYPES(cloth,          "cloth",                         solid/organic/cloth,                   bolt,             null)

DEFINE_STACK_SUBTYPES(dried_gut,      "dried gut",                     solid/organic/leather/gut,             thread,           null)

DEFINE_STACK_SUBTYPES(iron,           "iron",                          solid/metal/iron,                      bar,              null)
DEFINE_STACK_SUBTYPES(copper,         "copper",                        solid/metal/copper,                    bar,              null)

DEFINE_STACK_SUBTYPES(chipboard_oak,      "oak chipboard",             solid/organic/wood/chipboard,          sheet,            null)
DEFINE_STACK_SUBTYPES(chipboard_maple,    "maple chipboard",           solid/organic/wood/chipboard/maple,    sheet,            null)
DEFINE_STACK_SUBTYPES(chipboard_mahogany, "mahogany chipboard",        solid/organic/wood/chipboard/mahogany, sheet,            null)
DEFINE_STACK_SUBTYPES(chipboard_ebony,    "ebony chipboard",           solid/organic/wood/chipboard/ebony,    sheet,            null)
DEFINE_STACK_SUBTYPES(chipboard_walnut,   "walnut chipboard",          solid/organic/wood/chipboard/walnut,   sheet,            null)
DEFINE_STACK_SUBTYPES(chipboard_yew,      "yew chipboard",             solid/organic/wood/chipboard/yew,      sheet,            null)
