// Consider these images/atoms as part of the UI/HUD
#define APPEARANCE_UI_IGNORE_ALPHA RESET_COLOR|RESET_TRANSFORM|NO_CLIENT_COLOR|RESET_ALPHA|DEFAULT_APPEARANCE_FLAGS
#define APPEARANCE_UI              RESET_COLOR|RESET_TRANSFORM|NO_CLIENT_COLOR|DEFAULT_APPEARANCE_FLAGS
