#define COOKING_HEAT_ANY      0
#define COOKING_HEAT_DIRECT   1
#define COOKING_HEAT_INDIRECT 2

#define FOOD_RAW             -1
#define FOOD_PREPARED         0
#define FOOD_COOKED           1

#define INGREDIENT_FLAG_PLAIN     0
#define INGREDIENT_FLAG_MEAT      BITFLAG(0)
#define INGREDIENT_FLAG_FISH      BITFLAG(1)
#define INGREDIENT_FLAG_VEGETABLE BITFLAG(2)
#define INGREDIENT_FLAG_DAIRY     BITFLAG(3)
#define INGREDIENT_FLAG_EGG       BITFLAG(4)
#define INGREDIENT_FLAG_FRUIT     BITFLAG(5)
#define INGREDIENT_FLAG_GLUTEN    BITFLAG(6)
#define INGREDIENT_FLAG_SOY       BITFLAG(7)
#define INGREDIENT_FLAG_CAFFEINE  BITFLAG(8)
#define INGREDIENT_FLAG_FUNGI     BITFLAG(9)
#define INGREDIENT_FLAG_NUTS      BITFLAG(10)
#define INGREDIENT_FLAG_ALLIUM    BITFLAG(11)

#define INGREDIENT_FLAGS_ALL      (INGREDIENT_FLAG_MEAT|INGREDIENT_FLAG_FISH|INGREDIENT_FLAG_VEGETABLE|INGREDIENT_FLAG_DAIRY|INGREDIENT_FLAG_EGG|INGREDIENT_FLAG_FRUIT|INGREDIENT_FLAG_GLUTEN|INGREDIENT_FLAG_SOY|INGREDIENT_FLAG_CAFFEINE|INGREDIENT_FLAG_NUTS|INGREDIENT_FLAG_ALLIUM)
