// Keys used to set and retrieve icons from the UI decl system.
#define UI_ICON_INTERACTION "icon_interaction"
#define UI_ICON_ZONE_SELECT "icon_zone_sel"
#define UI_ICON_MOVEMENT    "icon_movement"
#define UI_ICON_INVENTORY   "icon_inventory"
#define UI_ICON_ATTACK      "icon_attack"
#define UI_ICON_HANDS       "icon_hands"
#define UI_ICON_INTERNALS   "icon_internals"
#define UI_ICON_HEALTH      "icon_health"
#define UI_ICON_CRIT_MARKER "icon_crit_marker"
#define UI_ICON_NUTRITION   "icon_nutrition"
#define UI_ICON_HYDRATION   "icon_hydration"
#define UI_ICON_FIRE_INTENT "icon_fire_intent"
#define UI_ICON_INTENT      "icon_intent"
#define UI_ICON_UP_HINT     "icon_uphint"
#define UI_ICON_STATUS      "icon_status"
#define UI_ICON_STATUS_FIRE "icon_status_fire"
#define UI_ICON_CHARGE      "icon_charge"