#define INTERACTION_NEEDS_ADJACENCY            BITFLAG(0)
#define INTERACTION_NEEDS_PHYSICAL_INTERACTION BITFLAG(1)
#define INTERACTION_NEEDS_TURF                 BITFLAG(2)
#define INTERACTION_NEEDS_INVENTORY            BITFLAG(3)
