#define TOOL_FLAG_WRENCH        "wrench"
#define TOOL_FLAG_SCREWDRIVER   "screwdriver"
#define TOOL_FLAG_CROWBAR       "crowbar"
#define TOOL_FLAG_WIRECUTTER    "wirecutter"
#define TOOL_FLAG_WELDER        "welder"
#define TOOL_FLAG_HATCHET       "hatchet"
