#define XENOFIND_APPLY_PREFIX BITFLAG(0)
#define XENOFIND_APPLY_DECOR  BITFLAG(1)
#define XENOFIND_REPLACE_ICON BITFLAG(2)

#define EFFECT_TOUCH    0
#define EFFECT_AURA     1
#define EFFECT_PULSE    2
#define MAX_EFFECT      2

#define EFFECT_UNKNOWN  0
#define EFFECT_ENERGY   1
#define EFFECT_PSIONIC  2
#define EFFECT_ELECTRO  3
#define EFFECT_PARTICLE 4
#define EFFECT_ORGANIC  5
#define EFFECT_SYNTH    6