/mob/living/death(gibbed, deathmessage="seizes up and falls limp...", show_dead_message)
	. = ..(gibbed, deathmessage, show_dead_message)
	if(buckled_mob)
		unbuckle_mob()
	if(hiding)
		hiding = FALSE
	var/obj/item/rig/rig = get_rig()
	if(rig)
		rig.notify_ai(SPAN_DANGER("Warning: user death event. Mobility control passed to integrated intelligence system."))
	if(.)
		stop_aiming(no_message=1)
