#define  SURGERY_SKILLS_GENERIC				list(SKILL_MEDICAL = SKILL_EXPERT)
#define  SURGERY_SKILLS_DELICATE			list(SKILL_MEDICAL = SKILL_EXPERT)
#define  SURGERY_SKILLS_ROBOTIC				list(SKILL_DEVICES = SKILL_ADEPT)
#define  SURGERY_SKILLS_ROBOTIC_ON_MEAT		list(SKILL_DEVICES = SKILL_ADEPT) 
