#define  SURGERY_SKILLS_GENERIC				list(SKILL_ANATOMY = SKILL_TRAINED, SKILL_MEDICAL = SKILL_EXPERIENCED)
#define  SURGERY_SKILLS_DELICATE			list(SKILL_ANATOMY = SKILL_EXPERIENCED, SKILL_MEDICAL = SKILL_EXPERIENCED)
#define  SURGERY_SKILLS_ROBOTIC				list(SKILL_DEVICES = SKILL_TRAINED)
#define  SURGERY_SKILLS_ROBOTIC_ON_MEAT		list(SKILL_ANATOMY = SKILL_TRAINED, SKILL_DEVICES = SKILL_TRAINED) 
