/proc/get_footstep_for_mob(var/footstep_type, var/mob/living/stepper)
	. = istype(stepper) && stepper.get_mob_footstep(footstep_type)
	if(!.)
		var/decl/footsteps/footsteps = GET_DECL(footstep_type)
		. = pick(footsteps.footstep_sounds)

/turf/proc/get_footstep_sound(var/mob/stepper)
	for(var/obj/structure/S in contents)
		if(S.footstep_type)
			return get_footstep_for_mob(S.footstep_type, stepper)
	if(check_fluid_depth(10) && !is_flooded(TRUE))
		return get_footstep_for_mob(/decl/footsteps/water, stepper)
	if(footstep_type)
		return get_footstep_for_mob(footstep_type, stepper)
	return get_footstep_for_mob(/decl/footsteps/blank, stepper)
