#define FABRICATOR_CLASS_GENERAL  "general"
#define FABRICATOR_CLASS_MICRO    "microlathe"
#define FABRICATOR_CLASS_FOOD     "food"
#define FABRICATOR_CLASS_PIPE     "pipe"
#define FABRICATOR_CLASS_DISPOSAL "disposal"
#define FABRICATOR_CLASS_BOOKS    "books"