/mob/living/silicon/pai/death(gibbed)
	. = ..()
	if(.)
		if(card)
			card.removePersonality()
			if(gibbed)
				dropInto(loc)
				qdel(card)
			else
				fold()
		if(mind)
			qdel(mind)
		ghostize()
		qdel(src)
