name: Compile changelogs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  CompileCL:
    runs-on: ubuntu-latest
    if: github.repository == 'NebulaSS13/Nebula' # to prevent this running on forks
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0 # Otherwise, we will fail to push refs
          ref: dev
          token: ${{ secrets.BOT_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@3105fb18c05ddd93efea5f9e0bef7a03a6e9e7df
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml bs4
      - name: Compile CL
        run: |
          python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs
      - name: Commit And Push
        run: |
          git config --local user.email "${{ secrets.BOT_EMAIL }}"
          git config --local user.name "${{ secrets.BOT_NAME }}"
          git commit -m "Automatic changelog generation [ci skip]" -a
          git push
